version: '2'
services:
  jenkins:
    image: pluhin31/jenkins_ci:latest
    container_name: jenkins_plu
    user: jenkins
    volumes:
      - /home/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    # environment:
    #   JENKINS_HOST_HOME: "/data/jenkins"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"
  icinga2:
    image: pluhin31/icinga2_agent:latest
    container_name: icinga2_agent
    ports:
    - "5665:5665"